issues_data = {   'CWE-200': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-200'},
    'CWE-215': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-215'},
    'CWE-250': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-250'},
    'CWE-276': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-276'},
    'CWE-295': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-295'},
    'CWE-326': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-326'},
    'CWE-327': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-327'},
    'CWE-329': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-329'},
    'CWE-330': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-330'},
    'CWE-494': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-494'},
    'CWE-502': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-502'},
    'CWE-532': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-532'},
    'CWE-611': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-611'},
    'CWE-695': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-695'},
    'CWE-749': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-749'},
    'CWE-78': {   'categories': ['security'],
                  'description': '%(issue.data)s',
                  'file': '%(issue.file)s',
                  'line': '%(issue.line)s',
                  'severity': 3,
                  'title': 'CWE-78'},
    'CWE-780': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-780'},
    'CWE-89': {   'categories': ['security'],
                  'description': '%(issue.data)s',
                  'file': '%(issue.file)s',
                  'line': '%(issue.line)s',
                  'severity': 3,
                  'title': 'CWE-89'},
    'CWE-919': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-91'}}
