issues_data = {   'E001': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Bad option.'},
    'E002': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Bad option value.'},
    'E003': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Expected a JSON value.'},
    'E004': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Input is neither a string nor an array of strings.'},
    'E005': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Input is empty.'},
    'E006': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Unexpected early end of program.'},
    'E007': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Missing "use strict" statement.'},
    'E008': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Strict violation.'},
    'E009': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': "Option 'validthis' can't be used in a global scope."},
    'E010': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': "'with' is not allowed in strict mode."},
    'E011': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'const variable has already been declared.'},
    'E012': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': "const variable is initialized to 'undefined'."},
    'E013': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Attempting to override a constant.'},
    'E014': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'A regular expression literal can be confused with '
                         "'/='."},
    'E015': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Unclosed regular expression.'},
    'E016': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Invalid regular expression.'},
    'E017': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Unclosed comment.'},
    'E018': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Unbegun comment.'},
    'E019': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Unmatched bracket.'},
    'E020': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Mismatching syntax.'},
    'E021': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Mismatching syntax.'},
    'E022': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Line breaking error.'},
    'E023': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Missing name/keyword.'},
    'E024': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Unexpected name/keyword.'},
    'E025': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': "Missing ':' on a case clause."},
    'E026': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': "Missing '}' to match '{'."},
    'E027': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': "Missing ']' to match '['."},
    'E028': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Illegal comma.'},
    'E029': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Unclosed string.'},
    'E030': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Expected an identifier.'},
    'E031': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Bad assignment.'},
    'E032': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': "Expected a small integer or 'false'."},
    'E033': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Expected an operator.'},
    'E034': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'get/set are ES5 features.'},
    'E035': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Missing property name.'},
    'E036': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Expected to see a statement and instead saw a '
                         'block.'},
    'E037': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Constant not declared correctly.'},
    'E038': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Variable not declared correctly.'},
    'E039': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Function declarations are not invocable. Wrap the '
                         'whole function invocation in parens.'},
    'E040': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Each value should have its own case label.'},
    'E041': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Unrecoverable syntax error.'},
    'E042': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Stopping.'},
    'E043': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Too many errors.'},
    'E044': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': "Variable was already defined and can't be "
                         'redefined.'},
    'E045': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Invalid for each loop.'},
    'E046': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'A yield statement shall be within a generator '
                         'function (with syntax: `function*`)'},
    'E047': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'A generator function shall contain a yield '
                         'statement.'},
    'E048': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Let declaration not directly within block.'},
    'E049': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Naming error.'},
    'I001': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': "Comma warnings can be turned off with 'laxcomma'."},
    'I002': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Reserved words as properties can be used under the '
                         "'es5' option."},
    'I003': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'ES5 option is now set per default'},
    'W001': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': "'hasOwnProperty' is a really bad name."},
    'W002': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Value of variable may be overwritten in IE 8 and '
                         'earlier.'},
    'W003': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Variable was used before it was defined.'},
    'W004': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Variable is already defined.'},
    'W005': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'A dot following a number can be confused with a '
                         'decimal point.'},
    'W006': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Confusing minuses.'},
    'W007': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Confusing pluses.'},
    'W008': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'A leading decimal point can be confused with a dot.'},
    'W009': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'The array literal notation [] is preferrable.'},
    'W010': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'The object literal notation {} is preferrable.'},
    'W011': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Unexpected following space.'},
    'W012': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Unexpected leading space.'},
    'W013': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Missing leading space.'},
    'W014': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Bad line breaking.'},
    'W015': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Unexpected indentation.'},
    'W016': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Unexpected use.'},
    'W017': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Bad operand.'},
    'W018': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Confusing use.'},
    'W019': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Use the isNaN function to compare with NaN.'},
    'W020': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Read only.'},
    'W021': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Variable is a function.'},
    'W022': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Do not assign to the exception parameter.'},
    'W023': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Expected an identifier in an assignment and instead '
                         'saw a function invocation.'},
    'W024': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Expected an identifier and instead saw a reserved '
                         'word.'},
    'W025': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Missing name in function declaration.'},
    'W026': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Inner functions should be listed at the top of the '
                         'outer function.'},
    'W027': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Unreachable code.'},
    'W028': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Unexpected label.'},
    'W030': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Expected an assignment or function call and instead '
                         'saw an expression.'},
    'W031': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': "Do not use 'new' for side effects."},
    'W032': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Unnecessary semicolon.'},
    'W033': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Missing semicolon.'},
    'W034': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Unnecessary directive.'},
    'W035': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Empty block.'},
    'W036': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Unexpected /*member.'},
    'W037': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Variable is already defined as a statement label.'},
    'W038': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Variable used out of scope.'},
    'W039': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': "'Value is not allowed."},
    'W040': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Possible strict violation.'},
    'W041': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Use of misleading/wrong comparison operator.'},
    'W042': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Avoid EOL escaping.'},
    'W043': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Bad escaping of EOL. Use option multistr if needed.'},
    'W044': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Bad or unnecessary escaping.'},
    'W045': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Bad number.'},
    'W046': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Use of extra leading zeros.'},
    'W047': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'A trailing decimal point can be confused with a '
                         'dot..'},
    'W048': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Unexpected control character in regular expression.'},
    'W049': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Unexpected escaped character.'},
    'W050': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'JavaScript URL.'},
    'W051': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Variables should not be deleted.'},
    'W052': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Unexpected value.'},
    'W053': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Do not use name/variable as a constructor.'},
    'W054': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'The Function constructor is a form of eval.'},
    'W055': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'A constructor name should start with an uppercase '
                         'letter.'},
    'W056': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Bad constructor.'},
    'W057': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': "Weird construction. Is 'new' unnecessary?"},
    'W058': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': "Missing '()' invoking a constructor."},
    'W059': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Avoid arguments.'},
    'W060': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'document.write can be a form of eval.'},
    'W061': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'eval can be harmful.'},
    'W062': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Wrap an immediate function invocation in parens to '
                         'assist the reader in understanding that the '
                         'expression is the result of a function, and not the '
                         'function itself.'},
    'W063': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Math is not a function.'},
    'W064': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': "Missing 'new' prefix when invoking a constructor."},
    'W065': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Missing radix parameter.'},
    'W066': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Implied eval. Consider passing a function instead of '
                         'a string.'},
    'W067': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Bad invocation.'},
    'W068': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Wrapping non-IIFE function literals in parens is '
                         'unnecessary.'},
    'W069': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Prefer dot notation.'},
    'W070': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Extra comma. (it breaks older versions of IE)'},
    'W071': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Function has too many statements.'},
    'W072': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Function has too many parameters.'},
    'W073': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Blocks are nested too deeply.'},
    'W074': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': "Function's cyclomatic complexity is too high."},
    'W075': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Duplicate key.'},
    'W076': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': "Unexpected parameter in 'get' function."},
    'W077': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': "Expected a single parameter in 'set' function."},
    'W078': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Setter is defined without getter.'},
    'W079': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Redefinition of variable.'},
    'W080': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': "Unneccessary initialization to 'undefined'."},
    'W081': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Too many var statements.'},
    'W082': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Function declarations should not be placed in '
                         'blocks. Use a function expression or move the '
                         'statement to the top of the outer function.'},
    'W083': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': "Don't make functions within a loop."},
    'W084': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Expected a conditional expression and instead saw an '
                         'assignment.'},
    'W085': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': "Don't use 'with'."},
    'W086': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': "Expected a 'break' statement."},
    'W087': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': "Forgotten 'debugger' statement?"},
    'W088': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': "Missing 'var' in 'for' loop."},
    'W089': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'The body of a for in should be wrapped in an if '
                         'statement to filter unwanted properties from the '
                         'prototype.'},
    'W090': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Using an undefined statement label.'},
    'W091': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Use of variable out of scope.'},
    'W092': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Wrap the /regexp/ literal in parens to disambiguate '
                         'the slash operator.'},
    'W093': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Did you mean to return a conditional instead of an '
                         'assignment?'},
    'W094': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Unexpected comma.'},
    'W095': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Expected a string.'},
    'W096': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Key may produce unexpected results.'},
    'W097': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Use the function form of "use strict".'},
    'W098': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Variable is defined but never used.'},
    'W099': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Mixed spaces and tabs.'},
    'W100': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'This character may get silently deleted by one or '
                         'more browsers.'},
    'W101': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Line is too long.'},
    'W102': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Trailing whitespace.'},
    'W103': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Property is deprecated.'},
    'W104': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Feature is only available in JavaScript 1.7.'},
    'W105': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Unexpected variable/name.'},
    'W106': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Identifier is not in camel case.'},
    'W107': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Script URL.'},
    'W108': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Strings must use doublequote.'},
    'W109': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Strings must use singlequote.'},
    'W110': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Mixed double and single quotes.'},
    'W112': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Unclosed string.'},
    'W113': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Control character in string.'},
    'W114': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 4,
                'title': 'Avoid variable/name.'},
    'W115': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Octal literals are not allowed in strict mode.'},
    'W116': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 2,
                'title': 'Expected variable/name.'},
    'W117': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Variable is not defined.'},
    'W118': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Variable/name is only available in Mozilla '
                         'JavaScript extensions (use moz option).'},
    'W119': {   'categories': [],
                'description': '%(issue.data.reason)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 1,
                'title': 'Variable/name is only available in ES6 (use esnext '
                         'option).'}}
