issues_data = {   'AWS': {   'categories': ['security'],
               'description': 'AWS',
               'file': '%(issue.file)s',
               'line': '%(issue.line)s',
               'severity': '1',
               'title': 'AWS'},
    'AWSAPIKey': {   'categories': ['security'],
                     'description': 'AWS API Key',
                     'file': '%(issue.file)s',
                     'line': '%(issue.line)s',
                     'severity': '1',
                     'title': 'AWS API Key'},
    'AdafruitAPIKey': {   'categories': ['security'],
                          'description': 'Adafruit API Key',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'Adafruit API Key'},
    'AdobeClientID(OAuthWeb)': {   'categories': ['security'],
                                   'description': 'Adobe Client ID (OAuth Web)',
                                   'file': '%(issue.file)s',
                                   'line': '%(issue.line)s',
                                   'severity': '1',
                                   'title': 'Adobe Client ID (OAuth Web)'},
    'AdobeClientSecret': {   'categories': ['security'],
                             'description': 'Adobe Client Secret',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Adobe Client Secret'},
    'Agesecretkey': {   'categories': ['security'],
                        'description': 'Age secret key',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': '1',
                        'title': 'Age secret key'},
    'AirtableAPIKey': {   'categories': ['security'],
                          'description': 'Airtable API Key',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'Airtable API Key'},
    'AlgoliaAPIKey': {   'categories': ['security'],
                         'description': 'Algolia API Key',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': '1',
                         'title': 'Algolia API Key'},
    'AlibabaAccessKeyID': {   'categories': ['security'],
                              'description': 'Alibaba AccessKey ID',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Alibaba AccessKey ID'},
    'AlibabaSecretKey': {   'categories': ['security'],
                            'description': 'Alibaba Secret Key',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'Alibaba Secret Key'},
    'AmazonAWSAccessKeyID': {   'categories': ['security'],
                                'description': 'Amazon AWS Access Key ID',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': '1',
                                'title': 'Amazon AWS Access Key ID'},
    'AsanaClientID': {   'categories': ['security'],
                         'description': 'Asana Client ID',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': '1',
                         'title': 'Asana Client ID'},
    'AsanaClientSecret': {   'categories': ['security'],
                             'description': 'Asana Client Secret',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Asana Client Secret'},
    'AtlassianAPItoken': {   'categories': ['security'],
                             'description': 'Atlassian API token',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Atlassian API token'},
    'BeamerAPItoken': {   'categories': ['security'],
                          'description': 'Beamer API token',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'Beamer API token'},
    'BitbucketClientID': {   'categories': ['security'],
                             'description': 'Bitbucket Client ID',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Bitbucket Client ID'},
    'BitbucketClientSecret': {   'categories': ['security'],
                                 'description': 'Bitbucket Client Secret',
                                 'file': '%(issue.file)s',
                                 'line': '%(issue.line)s',
                                 'severity': '1',
                                 'title': 'Bitbucket Client Secret'},
    'BittrexAccessKey': {   'categories': ['security'],
                            'description': 'Bittrex Access Key',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'Bittrex Access Key'},
    'BittrexSecretKey': {   'categories': ['security'],
                            'description': 'Bittrex Secret Key',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'Bittrex Secret Key'},
    'ClojarsAPItoken': {   'categories': ['security'],
                           'description': 'Clojars API token',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': '1',
                           'title': 'Clojars API token'},
    'CodecovAccessToken': {   'categories': ['security'],
                              'description': 'Codecov Access Token',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Codecov Access Token'},
    'CoinbaseAccessToken': {   'categories': ['security'],
                               'description': 'Coinbase Access Token',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': '1',
                               'title': 'Coinbase Access Token'},
    'ConfluentAccessToken': {   'categories': ['security'],
                                'description': 'Confluent Access Token',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': '1',
                                'title': 'Confluent Access Token'},
    'ConfluentSecretKey': {   'categories': ['security'],
                              'description': 'Confluent Secret Key',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Confluent Secret Key'},
    'ContentfuldeliveryAPItoken': {   'categories': ['security'],
                                      'description': 'Contentful delivery API '
                                                     'token',
                                      'file': '%(issue.file)s',
                                      'line': '%(issue.line)s',
                                      'severity': '1',
                                      'title': 'Contentful delivery API token'},
    'DatabricksAPItoken': {   'categories': ['security'],
                              'description': 'Databricks API token',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Databricks API token'},
    'DatadogAccessToken': {   'categories': ['security'],
                              'description': 'Datadog Access Token',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Datadog Access Token'},
    'DiscordAPIkey': {   'categories': ['security'],
                         'description': 'Discord API key',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': '1',
                         'title': 'Discord API key'},
    'DiscordclientID': {   'categories': ['security'],
                           'description': 'Discord client ID',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': '1',
                           'title': 'Discord client ID'},
    'Discordclientsecret': {   'categories': ['security'],
                               'description': 'Discord client secret',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': '1',
                               'title': 'Discord client secret'},
    'DopplerAPItoken': {   'categories': ['security'],
                           'description': 'Doppler API token',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': '1',
                           'title': 'Doppler API token'},
    'DroneciAccessToken': {   'categories': ['security'],
                              'description': 'Droneci Access Token',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Droneci Access Token'},
    'DropboxAPIsecret': {   'categories': ['security'],
                            'description': 'Dropbox API secret',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'Dropbox API secret'},
    'DropboxlonglivedAPItoken': {   'categories': ['security'],
                                    'description': 'Dropbox long lived API '
                                                   'token',
                                    'file': '%(issue.file)s',
                                    'line': '%(issue.line)s',
                                    'severity': '1',
                                    'title': 'Dropbox long lived API token'},
    'DropboxshortlivedAPItoken': {   'categories': ['security'],
                                     'description': 'Dropbox short lived API '
                                                    'token',
                                     'file': '%(issue.file)s',
                                     'line': '%(issue.line)s',
                                     'severity': '1',
                                     'title': 'Dropbox short lived API token'},
    'DuffelAPItoken': {   'categories': ['security'],
                          'description': 'Duffel API token',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'Duffel API token'},
    'DynatraceAPItoken': {   'categories': ['security'],
                             'description': 'Dynatrace API token',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Dynatrace API token'},
    'EasyPostAPItoken': {   'categories': ['security'],
                            'description': 'EasyPost API token',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'EasyPost API token'},
    'EasyPosttestAPItoken': {   'categories': ['security'],
                                'description': 'EasyPost test API token',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': '1',
                                'title': 'EasyPost test API token'},
    'EtsyAccessToken': {   'categories': ['security'],
                           'description': 'Etsy Access Token',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': '1',
                           'title': 'Etsy Access Token'},
    'Facebook': {   'categories': ['security'],
                    'description': 'Facebook',
                    'file': '%(issue.file)s',
                    'line': '%(issue.line)s',
                    'severity': '1',
                    'title': 'Facebook'},
    'FastlyAPIkey': {   'categories': ['security'],
                        'description': 'Fastly API key',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': '1',
                        'title': 'Fastly API key'},
    'FinicityAPItoken': {   'categories': ['security'],
                            'description': 'Finicity API token',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'Finicity API token'},
    'FinicityClientSecret': {   'categories': ['security'],
                                'description': 'Finicity Client Secret',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': '1',
                                'title': 'Finicity Client Secret'},
    'FinicityPublicKey': {   'categories': ['security'],
                             'description': 'Finicity Public Key',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Finicity Public Key'},
    'FinnhubAccessToken': {   'categories': ['security'],
                              'description': 'Finnhub Access Token',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Finnhub Access Token'},
    'FlickrAccessToken': {   'categories': ['security'],
                             'description': 'Flickr Access Token',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Flickr Access Token'},
    'FlutterwaveEncryptionKey': {   'categories': ['security'],
                                    'description': 'Flutterwave Encryption Key',
                                    'file': '%(issue.file)s',
                                    'line': '%(issue.line)s',
                                    'severity': '1',
                                    'title': 'Flutterwave Encryption Key'},
    'FlutterwaveSecretKey': {   'categories': ['security'],
                                'description': 'Flutterwave Secret Key',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': '1',
                                'title': 'Flutterwave Secret Key'},
    'Frame.ioAPItoken': {   'categories': ['security'],
                            'description': 'Frame.io API token',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'Frame.io API token'},
    'FreshbooksAccessToken': {   'categories': ['security'],
                                 'description': 'Freshbooks Access Token',
                                 'file': '%(issue.file)s',
                                 'line': '%(issue.line)s',
                                 'severity': '1',
                                 'title': 'Freshbooks Access Token'},
    'GCPAPIkey': {   'categories': ['security'],
                     'description': 'GCP API key',
                     'file': '%(issue.file)s',
                     'line': '%(issue.line)s',
                     'severity': '1',
                     'title': 'GCP API key'},
    'GenericSecret': {   'categories': ['security'],
                         'description': 'Generic Secret',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': '1',
                         'title': 'Generic Secret'},
    'GitHub': {   'categories': ['security'],
                  'description': 'GitHub',
                  'file': '%(issue.file)s',
                  'line': '%(issue.line)s',
                  'severity': '1',
                  'title': 'GitHub'},
    'GitHubAppToken': {   'categories': ['security'],
                          'description': 'GitHub App Token',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'GitHub App Token'},
    'GitHubOAuthAccessToken': {   'categories': ['security'],
                                  'description': 'GitHub OAuth Access Token',
                                  'file': '%(issue.file)s',
                                  'line': '%(issue.line)s',
                                  'severity': '1',
                                  'title': 'GitHub OAuth Access Token'},
    'GitHubPersonalAccessToken': {   'categories': ['security'],
                                     'description': 'GitHub Personal Access '
                                                    'Token',
                                     'file': '%(issue.file)s',
                                     'line': '%(issue.line)s',
                                     'severity': '1',
                                     'title': 'GitHub Personal Access Token'},
    'GitHubRefreshToken': {   'categories': ['security'],
                              'description': 'GitHub Refresh Token',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'GitHub Refresh Token'},
    'GitLabPersonalAccessToken': {   'categories': ['security'],
                                     'description': 'GitLab Personal Access '
                                                    'Token',
                                     'file': '%(issue.file)s',
                                     'line': '%(issue.line)s',
                                     'severity': '1',
                                     'title': 'GitLab Personal Access Token'},
    'GitterAccessToken': {   'categories': ['security'],
                             'description': 'Gitter Access Token',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Gitter Access Token'},
    'GoCardlessAPItoken': {   'categories': ['security'],
                              'description': 'GoCardless API token',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'GoCardless API token'},
    'Google(GCP)Service-account': {   'categories': ['security'],
                                      'description': 'Google(GCP) '
                                                     'Service-account',
                                      'file': '%(issue.file)s',
                                      'line': '%(issue.line)s',
                                      'severity': '1',
                                      'title': 'Google(GCP) Service-account'},
    'GoogleAPIKey': {   'categories': ['security'],
                        'description': 'Google API Key',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': '1',
                        'title': 'Google API Key'},
    'HashiCorpTerraformuser/orgAPItoken': {   'categories': ['security'],
                                              'description': 'HashiCorp '
                                                             'Terraform '
                                                             'user/org API '
                                                             'token',
                                              'file': '%(issue.file)s',
                                              'line': '%(issue.line)s',
                                              'severity': '1',
                                              'title': 'HashiCorp Terraform '
                                                       'user/org API token'},
    'HerokuAPIKey': {   'categories': ['security'],
                        'description': 'Heroku API Key',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': '1',
                        'title': 'Heroku API Key'},
    'HubSpotAPIToken': {   'categories': ['security'],
                           'description': 'HubSpot API Token',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': '1',
                           'title': 'HubSpot API Token'},
    'IntercomAPIToken': {   'categories': ['security'],
                            'description': 'Intercom API Token',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'Intercom API Token'},
    'KrakenAccessToken': {   'categories': ['security'],
                             'description': 'Kraken Access Token',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Kraken Access Token'},
    'KucoinAccessToken': {   'categories': ['security'],
                             'description': 'Kucoin Access Token',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Kucoin Access Token'},
    'KucoinSecretKey': {   'categories': ['security'],
                           'description': 'Kucoin Secret Key',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': '1',
                           'title': 'Kucoin Secret Key'},
    'LaunchdarklyAccessToken': {   'categories': ['security'],
                                   'description': 'Launchdarkly Access Token',
                                   'file': '%(issue.file)s',
                                   'line': '%(issue.line)s',
                                   'severity': '1',
                                   'title': 'Launchdarkly Access Token'},
    'LinearAPIToken': {   'categories': ['security'],
                          'description': 'Linear API Token',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'Linear API Token'},
    'LinearClientSecret': {   'categories': ['security'],
                              'description': 'Linear Client Secret',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Linear Client Secret'},
    'LinkedInClientID': {   'categories': ['security'],
                            'description': 'LinkedIn Client ID',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'LinkedIn Client ID'},
    'LinkedInClientsecret': {   'categories': ['security'],
                                'description': 'LinkedIn Client secret',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': '1',
                                'title': 'LinkedIn Client secret'},
    'LobAPIKey': {   'categories': ['security'],
                     'description': 'Lob API Key',
                     'file': '%(issue.file)s',
                     'line': '%(issue.line)s',
                     'severity': '1',
                     'title': 'Lob API Key'},
    'LobPublishableAPIKey': {   'categories': ['security'],
                                'description': 'Lob Publishable API Key',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': '1',
                                'title': 'Lob Publishable API Key'},
    'MailchimpAPIkey': {   'categories': ['security'],
                           'description': 'Mailchimp API key',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': '1',
                           'title': 'Mailchimp API key'},
    'MailgunprivateAPItoken': {   'categories': ['security'],
                                  'description': 'Mailgun private API token',
                                  'file': '%(issue.file)s',
                                  'line': '%(issue.line)s',
                                  'severity': '1',
                                  'title': 'Mailgun private API token'},
    'Mailgunpublicvalidationkey': {   'categories': ['security'],
                                      'description': 'Mailgun public '
                                                     'validation key',
                                      'file': '%(issue.file)s',
                                      'line': '%(issue.line)s',
                                      'severity': '1',
                                      'title': 'Mailgun public validation key'},
    'Mailgunwebhooksigningkey': {   'categories': ['security'],
                                    'description': 'Mailgun webhook signing '
                                                   'key',
                                    'file': '%(issue.file)s',
                                    'line': '%(issue.line)s',
                                    'severity': '1',
                                    'title': 'Mailgun webhook signing key'},
    'MapBoxAPItoken': {   'categories': ['security'],
                          'description': 'MapBox API token',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'MapBox API token'},
    'MattermostAccessToken': {   'categories': ['security'],
                                 'description': 'Mattermost Access Token',
                                 'file': '%(issue.file)s',
                                 'line': '%(issue.line)s',
                                 'severity': '1',
                                 'title': 'Mattermost Access Token'},
    'MessageBirdAPItoken': {   'categories': ['security'],
                               'description': 'MessageBird API token',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': '1',
                               'title': 'MessageBird API token'},
    'MessageBirdclientID': {   'categories': ['security'],
                               'description': 'MessageBird client ID',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': '1',
                               'title': 'MessageBird client ID'},
    'NetlifyAccessToken': {   'categories': ['security'],
                              'description': 'Netlify Access Token',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Netlify Access Token'},
    'NewRelicingestbrowserAPItoken': {   'categories': ['security'],
                                         'description': 'New Relic ingest '
                                                        'browser API token',
                                         'file': '%(issue.file)s',
                                         'line': '%(issue.line)s',
                                         'severity': '1',
                                         'title': 'New Relic ingest browser '
                                                  'API token'},
    'NewRelicuserAPIID': {   'categories': ['security'],
                             'description': 'New Relic user API ID',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'New Relic user API ID'},
    'NewRelicuserAPIKey': {   'categories': ['security'],
                              'description': 'New Relic user API Key',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'New Relic user API Key'},
    'NytimesAccessToken': {   'categories': ['security'],
                              'description': 'Nytimes Access Token',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Nytimes Access Token'},
    'OktaAccessToken': {   'categories': ['security'],
                           'description': 'Okta Access Token',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': '1',
                           'title': 'Okta Access Token'},
    'PasswordinURL': {   'categories': ['security'],
                         'description': 'Password in URL',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': '1',
                         'title': 'Password in URL'},
    'PlaidAPIToken': {   'categories': ['security'],
                         'description': 'Plaid API Token',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': '1',
                         'title': 'Plaid API Token'},
    'PlaidClientID': {   'categories': ['security'],
                         'description': 'Plaid Client ID',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': '1',
                         'title': 'Plaid Client ID'},
    'PlaidSecretkey': {   'categories': ['security'],
                          'description': 'Plaid Secret key',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'Plaid Secret key'},
    'PlanetScaleAPItoken': {   'categories': ['security'],
                               'description': 'PlanetScale API token',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': '1',
                               'title': 'PlanetScale API token'},
    'PlanetScaleOAuthtoken': {   'categories': ['security'],
                                 'description': 'PlanetScale OAuth token',
                                 'file': '%(issue.file)s',
                                 'line': '%(issue.line)s',
                                 'severity': '1',
                                 'title': 'PlanetScale OAuth token'},
    'PlanetScalepassword': {   'categories': ['security'],
                               'description': 'PlanetScale password',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': '1',
                               'title': 'PlanetScale password'},
    'PostmanAPItoken': {   'categories': ['security'],
                           'description': 'Postman API token',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': '1',
                           'title': 'Postman API token'},
    'PrivateKey': {   'categories': ['security'],
                      'description': 'Private Key',
                      'file': '%(issue.file)s',
                      'line': '%(issue.line)s',
                      'severity': '1',
                      'title': 'Private Key'},
    'PulumiAPItoken': {   'categories': ['security'],
                          'description': 'Pulumi API token',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'Pulumi API token'},
    'PyPIuploadtoken': {   'categories': ['security'],
                           'description': 'PyPI upload token',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': '1',
                           'title': 'PyPI upload token'},
    'RSAprivatekey': {   'categories': ['security'],
                         'description': 'RSA private key',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': '1',
                         'title': 'RSA private key'},
    'RapidAPIAccessToken': {   'categories': ['security'],
                               'description': 'RapidAPI Access Token',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': '1',
                               'title': 'RapidAPI Access Token'},
    'RubygemAPItoken': {   'categories': ['security'],
                           'description': 'Rubygem API token',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': '1',
                           'title': 'Rubygem API token'},
    'SendGridAPItoken': {   'categories': ['security'],
                            'description': 'SendGrid API token',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'SendGrid API token'},
    'SendbirdAccessID': {   'categories': ['security'],
                            'description': 'Sendbird Access ID',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'Sendbird Access ID'},
    'SendbirdAccessToken': {   'categories': ['security'],
                               'description': 'Sendbird Access Token',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': '1',
                               'title': 'Sendbird Access Token'},
    'SendinblueAPItoken': {   'categories': ['security'],
                              'description': 'Sendinblue API token',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Sendinblue API token'},
    'SentryAccessToken': {   'categories': ['security'],
                             'description': 'Sentry Access Token',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Sentry Access Token'},
    'ShippoAPItoken': {   'categories': ['security'],
                          'description': 'Shippo API token',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'Shippo API token'},
    'Shopifyaccesstoken': {   'categories': ['security'],
                              'description': 'Shopify access token',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Shopify access token'},
    'Shopifycustomaccesstoken': {   'categories': ['security'],
                                    'description': 'Shopify custom access '
                                                   'token',
                                    'file': '%(issue.file)s',
                                    'line': '%(issue.line)s',
                                    'severity': '1',
                                    'title': 'Shopify custom access token'},
    'Shopifyprivateappaccesstoken': {   'categories': ['security'],
                                        'description': 'Shopify private app '
                                                       'access token',
                                        'file': '%(issue.file)s',
                                        'line': '%(issue.line)s',
                                        'severity': '1',
                                        'title': 'Shopify private app access '
                                                 'token'},
    'Shopifysharedsecret': {   'categories': ['security'],
                               'description': 'Shopify shared secret',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': '1',
                               'title': 'Shopify shared secret'},
    'SlackToken': {   'categories': ['security'],
                      'description': 'Slack Token',
                      'file': '%(issue.file)s',
                      'line': '%(issue.line)s',
                      'severity': '1',
                      'title': 'Slack Token'},
    'SlackWebhook': {   'categories': ['security'],
                        'description': 'Slack Webhook',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': '1',
                        'title': 'Slack Webhook'},
    'Slacktoken': {   'categories': ['security'],
                      'description': 'Slack token',
                      'file': '%(issue.file)s',
                      'line': '%(issue.line)s',
                      'severity': '1',
                      'title': 'Slack token'},
    'SquareAccessToken': {   'categories': ['security'],
                             'description': 'Square Access Token',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Square Access Token'},
    'SquarespaceAccessToken': {   'categories': ['security'],
                                  'description': 'Squarespace Access Token',
                                  'file': '%(issue.file)s',
                                  'line': '%(issue.line)s',
                                  'severity': '1',
                                  'title': 'Squarespace Access Token'},
    'Stripe': {   'categories': ['security'],
                  'description': 'Stripe',
                  'file': '%(issue.file)s',
                  'line': '%(issue.line)s',
                  'severity': '1',
                  'title': 'Stripe'},
    'StripeAPIKey': {   'categories': ['security'],
                        'description': 'Stripe API Key',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': '1',
                        'title': 'Stripe API Key'},
    'SumoLogicAccessID': {   'categories': ['security'],
                             'description': 'SumoLogic Access ID',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'SumoLogic Access ID'},
    'SumoLogicAccessToken': {   'categories': ['security'],
                                'description': 'SumoLogic Access Token',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': '1',
                                'title': 'SumoLogic Access Token'},
    'TravisCIAccessToken': {   'categories': ['security'],
                               'description': 'Travis CI Access Token',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': '1',
                               'title': 'Travis CI Access Token'},
    'TwilioAPIKey': {   'categories': ['security'],
                        'description': 'Twilio API Key',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': '1',
                        'title': 'Twilio API Key'},
    'TwitchAPItoken': {   'categories': ['security'],
                          'description': 'Twitch API token',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'Twitch API token'},
    'TwitterAPIKey': {   'categories': ['security'],
                         'description': 'Twitter API Key',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': '1',
                         'title': 'Twitter API Key'},
    'TwitterAPISecret': {   'categories': ['security'],
                            'description': 'Twitter API Secret',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'Twitter API Secret'},
    'TwitterAccessSecret': {   'categories': ['security'],
                               'description': 'Twitter Access Secret',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': '1',
                               'title': 'Twitter Access Secret'},
    'TwitterAccessToken': {   'categories': ['security'],
                              'description': 'Twitter Access Token',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Twitter Access Token'},
    'TwitterBearerToken': {   'categories': ['security'],
                              'description': 'Twitter Bearer Token',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': '1',
                              'title': 'Twitter Bearer Token'},
    'TwitterOAuth': {   'categories': ['security'],
                        'description': 'Twitter OAuth',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': '1',
                        'title': 'Twitter OAuth'},
    'TypeformAPItoken': {   'categories': ['security'],
                            'description': 'Typeform API token',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'Typeform API token'},
    'YandexAPIKey': {   'categories': ['security'],
                        'description': 'Yandex API Key',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': '1',
                        'title': 'Yandex API Key'},
    'YandexAWSAccessToken': {   'categories': ['security'],
                                'description': 'Yandex AWS Access Token',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': '1',
                                'title': 'Yandex AWS Access Token'},
    'YandexAccessToken': {   'categories': ['security'],
                             'description': 'Yandex Access Token',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Yandex Access Token'},
    'ZendeskSecretKey': {   'categories': ['security'],
                            'description': 'Zendesk Secret Key',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'Zendesk Secret Key'},
    'npmaccesstoken': {   'categories': ['security'],
                          'description': 'npm access token',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'npm access token'}}
