issues_data = {   'ApexBadCrypto': {   'categories': ['security'],
                         'description': '%(issue.data)s',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': 3,
                         'title': 'ApexBadCrypto'},
    'ApexCRUDViolation': {   'categories': ['security'],
                             'description': '%(issue.data)s',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': 3,
                             'title': 'ApexCRUDViolation'},
    'ApexCSRF': {   'categories': ['security'],
                    'description': '%(issue.data)s',
                    'file': '%(issue.file)s',
                    'line': '%(issue.line)s',
                    'severity': 3,
                    'title': 'ApexCSRF'},
    'ApexDangerousMethods': {   'categories': ['security'],
                                'description': '%(issue.data)s',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': 3,
                                'title': 'ApexDangerousMethods'},
    'ApexDoc': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'ApexDoc'},
    'ApexInsecureEndpoint': {   'categories': ['security'],
                                'description': '%(issue.data)s',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': 3,
                                'title': 'ApexInsecureEndpoint'},
    'ApexOpenRedirect': {   'categories': ['security'],
                            'description': '%(issue.data)s',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': 3,
                            'title': 'ApexOpenRedirect'},
    'ApexSOQLInjection': {   'categories': ['security'],
                             'description': '%(issue.data)s',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': 3,
                             'title': 'ApexSOQLInjection'},
    'ApexSharingViolations': {   'categories': ['security'],
                                 'description': '%(issue.data)s',
                                 'file': '%(issue.file)s',
                                 'line': '%(issue.line)s',
                                 'severity': 3,
                                 'title': 'ApexSharingViolations'},
    'ApexSuggestUsingNamedCred': {   'categories': ['security'],
                                     'description': '%(issue.data)s',
                                     'file': '%(issue.file)s',
                                     'line': '%(issue.line)s',
                                     'severity': 3,
                                     'title': 'ApexSuggestUsingNamedCred'},
    'ApexUnitTestClassShouldHaveAsserts': {   'categories': ['security'],
                                              'description': '%(issue.data)s',
                                              'file': '%(issue.file)s',
                                              'line': '%(issue.line)s',
                                              'severity': 3,
                                              'title': 'ApexUnitTestClassShouldHaveAsserts'},
    'ApexUnitTestShouldNotUseSeeAllDataTrue': {   'categories': ['security'],
                                                  'description': '%(issue.data)s',
                                                  'file': '%(issue.file)s',
                                                  'line': '%(issue.line)s',
                                                  'severity': 3,
                                                  'title': 'ApexUnitTestShouldNotUseSeeAllDataTrue'},
    'ApexXSSFromEscapeFalse': {   'categories': ['security'],
                                  'description': '%(issue.data)s',
                                  'file': '%(issue.file)s',
                                  'line': '%(issue.line)s',
                                  'severity': 3,
                                  'title': 'ApexXSSFromEscapeFalse'},
    'ApexXSSFromURLParam': {   'categories': ['security'],
                               'description': '%(issue.data)s',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': 3,
                               'title': 'ApexXSSFromURLParam'},
    'AvoidDeeplyNestedIfStmts': {   'categories': ['security'],
                                    'description': '%(issue.data)s',
                                    'file': '%(issue.file)s',
                                    'line': '%(issue.line)s',
                                    'severity': 3,
                                    'title': 'AvoidDeeplyNestedIfStmts'},
    'AvoidDirectAccessTriggerMap': {   'categories': ['security'],
                                       'description': '%(issue.data)s',
                                       'file': '%(issue.file)s',
                                       'line': '%(issue.line)s',
                                       'severity': 3,
                                       'title': 'AvoidDirectAccessTriggerMap'},
    'AvoidGlobalModifier': {   'categories': ['security'],
                               'description': '%(issue.data)s',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': 3,
                               'title': 'AvoidGlobalModifier'},
    'AvoidHardcodingId': {   'categories': ['security'],
                             'description': '%(issue.data)s',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': 3,
                             'title': 'AvoidHardcodingId'},
    'AvoidLogicInTrigger': {   'categories': ['security'],
                               'description': '%(issue.data)s',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': 3,
                               'title': 'AvoidLogicInTrigger'},
    'AvoidNonExistentAnnotations': {   'categories': ['security'],
                                       'description': '%(issue.data)s',
                                       'file': '%(issue.file)s',
                                       'line': '%(issue.line)s',
                                       'severity': 3,
                                       'title': 'AvoidNonExistentAnnotations'},
    'ClassNamingConventions': {   'categories': ['security'],
                                  'description': '%(issue.data)s',
                                  'file': '%(issue.file)s',
                                  'line': '%(issue.line)s',
                                  'severity': 3,
                                  'title': 'ClassNamingConventions'},
    'CyclomaticComplexity': {   'categories': ['security'],
                                'description': '%(issue.data)s',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': 3,
                                'title': 'ExcessiveClassLength'},
    'DebugsShouldUseLoggingLevel': {   'categories': ['security'],
                                       'description': '%(issue.data)s',
                                       'file': '%(issue.file)s',
                                       'line': '%(issue.line)s',
                                       'severity': 3,
                                       'title': 'DebugsShouldUseLoggingLevel'},
    'EmptyCatchBlock': {   'categories': ['security'],
                           'description': '%(issue.data)s',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': 3,
                           'title': 'EmptyCatchBlock'},
    'EmptyIfStmt': {   'categories': ['security'],
                       'description': '%(issue.data)s',
                       'file': '%(issue.file)s',
                       'line': '%(issue.line)s',
                       'severity': 3,
                       'title': 'EmptyIfStmt'},
    'EmptyStatementBlock': {   'categories': ['security'],
                               'description': '%(issue.data)s',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': 3,
                               'title': 'EmptyStatementBlock'},
    'EmptyTryOrFinallyBlock': {   'categories': ['security'],
                                  'description': '%(issue.data)s',
                                  'file': '%(issue.file)s',
                                  'line': '%(issue.line)s',
                                  'severity': 3,
                                  'title': 'EmptyTryOrFinallyBlock'},
    'EmptyWhileStmt': {   'categories': ['security'],
                          'description': '%(issue.data)s',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': 3,
                          'title': 'EmptyWhileStmt'},
    'ExcessiveClassLength': {   'categories': ['security'],
                                'description': '%(issue.data)s',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': 3,
                                'title': 'ExcessiveClassLength'},
    'ExcessiveParameterList': {   'categories': ['security'],
                                  'description': '%(issue.data)s',
                                  'file': '%(issue.file)s',
                                  'line': '%(issue.line)s',
                                  'severity': 3,
                                  'title': 'ExcessiveParameterList'},
    'ExcessivePublicCount': {   'categories': ['security'],
                                'description': '%(issue.data)s',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': 3,
                                'title': 'ExcessivePublicCount'},
    'FieldNamingConventions': {   'categories': ['security'],
                                  'description': '%(issue.data)s',
                                  'file': '%(issue.file)s',
                                  'line': '%(issue.line)s',
                                  'severity': 3,
                                  'title': 'FieldNamingConventions'},
    'ForLoopsMustUseBraces': {   'categories': ['security'],
                                 'description': '%(issue.data)s',
                                 'file': '%(issue.file)s',
                                 'line': '%(issue.line)s',
                                 'severity': 3,
                                 'title': 'ForLoopsMustUseBraces'},
    'FormalParameterNamingConventions': {   'categories': ['security'],
                                            'description': '%(issue.data)s',
                                            'file': '%(issue.file)s',
                                            'line': '%(issue.line)s',
                                            'severity': 3,
                                            'title': 'FormalParameterNamingConventions'},
    'IfElseStmtsMustUseBraces': {   'categories': ['security'],
                                    'description': '%(issue.data)s',
                                    'file': '%(issue.file)s',
                                    'line': '%(issue.line)s',
                                    'severity': 3,
                                    'title': 'IfElseStmtsMustUseBraces'},
    'IfStmtsMustUseBraces': {   'categories': ['security'],
                                'description': '%(issue.data)s',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': 3,
                                'title': 'IfStmtsMustUseBraces'},
    'LocalVariableNamingConventions': {   'categories': ['security'],
                                          'description': '%(issue.data)s',
                                          'file': '%(issue.file)s',
                                          'line': '%(issue.line)s',
                                          'severity': 3,
                                          'title': 'LocalVariableNamingConventions'},
    'MethodNamingConventions': {   'categories': ['security'],
                                   'description': '%(issue.data)s',
                                   'file': '%(issue.file)s',
                                   'line': '%(issue.line)s',
                                   'severity': 3,
                                   'title': 'MethodNamingConventions'},
    'MethodWithSameNameAsEnclosingClass': {   'categories': ['security'],
                                              'description': '%(issue.data)s',
                                              'file': '%(issue.file)s',
                                              'line': '%(issue.line)s',
                                              'severity': 3,
                                              'title': 'MethodWithSameNameAsEnclosingClass'},
    'NcssConstructorCount': {   'categories': ['security'],
                                'description': '%(issue.data)s',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': 3,
                                'title': 'NcssConstructorCount'},
    'NcssMethodCount': {   'categories': ['security'],
                           'description': '%(issue.data)s',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': 3,
                           'title': 'NcssMethodCount'},
    'NcssTypeCount': {   'categories': ['security'],
                         'description': '%(issue.data)s',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': 3,
                         'title': 'NcssTypeCount'},
    'OneDeclarationPerLine': {   'categories': ['security'],
                                 'description': '%(issue.data)s',
                                 'file': '%(issue.file)s',
                                 'line': '%(issue.line)s',
                                 'severity': 3,
                                 'title': 'OneDeclarationPerLine'},
    'OperationWithLimitsInLoop': {   'categories': ['security'],
                                     'description': '%(issue.data)s',
                                     'file': '%(issue.file)s',
                                     'line': '%(issue.line)s',
                                     'severity': 3,
                                     'title': 'OperationWithLimitsInLoop'},
    'PropertyNamingConventions': {   'categories': ['security'],
                                     'description': '%(issue.data)s',
                                     'file': '%(issue.file)s',
                                     'line': '%(issue.line)s',
                                     'severity': 3,
                                     'title': 'PropertyNamingConventions'},
    'StdCyclomaticComplexity': {   'categories': ['security'],
                                   'description': '%(issue.data)s',
                                   'file': '%(issue.file)s',
                                   'line': '%(issue.line)s',
                                   'severity': 3,
                                   'title': 'StdCyclomaticComplexity'},
    'TooManyFields': {   'categories': ['security'],
                         'description': '%(issue.data)s',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': 3,
                         'title': 'TooManyFields'},
    'WhileLoopsMustUseBraces': {   'categories': ['security'],
                                   'description': '%(issue.data)s',
                                   'file': '%(issue.file)s',
                                   'line': '%(issue.line)s',
                                   'severity': 3,
                                   'title': 'WhileLoopsMustUseBraces'}}
