issues_data = {   'BasicAuth': {   'categories': ['security'],
                     'description': '%(issue.data)s',
                     'file': '%(issue.file)s',
                     'line': '%(issue.line)s',
                     'severity': 3,
                     'title': 'BasicAuth'},
    'BasicAuthTimingAttack': {   'categories': ['security'],
                                 'description': '%(issue.data)s',
                                 'file': '%(issue.file)s',
                                 'line': '%(issue.line)s',
                                 'severity': 3,
                                 'title': 'BasicAuthTimingAttack'},
    'ContentTag': {   'categories': ['security'],
                      'description': '%(issue.data)s',
                      'file': '%(issue.file)s',
                      'line': '%(issue.line)s',
                      'severity': 3,
                      'title': 'ContentTag'},
    'CreateWith': {   'categories': ['security'],
                      'description': '%(issue.data)s',
                      'file': '%(issue.file)s',
                      'line': '%(issue.line)s',
                      'severity': 3,
                      'title': 'CreateWith'},
    'CrossSiteScripting': {   'categories': ['security'],
                              'description': '%(issue.data)s',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': 3,
                              'title': 'CrossSiteScripting'},
    'DefaultRoutes': {   'categories': ['security'],
                         'description': '%(issue.data)s',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': 3,
                         'title': 'DefaultRoutes'},
    'Deserialize': {   'categories': ['security'],
                       'description': '%(issue.data)s',
                       'file': '%(issue.file)s',
                       'line': '%(issue.line)s',
                       'severity': 3,
                       'title': 'Deserialize'},
    'DetailedExceptions': {   'categories': ['security'],
                              'description': '%(issue.data)s',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': 3,
                              'title': 'DetailedExceptions'},
    'DigestDoS': {   'categories': ['security'],
                     'description': '%(issue.data)s',
                     'file': '%(issue.file)s',
                     'line': '%(issue.line)s',
                     'severity': 3,
                     'title': 'DigestDoS'},
    'DynamicFinders': {   'categories': ['security'],
                          'description': '%(issue.data)s',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': 3,
                          'title': 'DynamicFinders'},
    'EscapeFunction': {   'categories': ['security'],
                          'description': '%(issue.data)s',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': 3,
                          'title': 'EscapeFunction'},
    'Evaluation': {   'categories': ['security'],
                      'description': '%(issue.data)s',
                      'file': '%(issue.file)s',
                      'line': '%(issue.line)s',
                      'severity': 3,
                      'title': 'Evaluation'},
    'Execute': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'Execute'},
    'FileAccess': {   'categories': ['security'],
                      'description': '%(issue.data)s',
                      'file': '%(issue.file)s',
                      'line': '%(issue.line)s',
                      'severity': 3,
                      'title': 'FileAccess'},
    'FileDisclosure': {   'categories': ['security'],
                          'description': '%(issue.data)s',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': 3,
                          'title': 'FileDisclosure'},
    'FilterSkipping': {   'categories': ['security'],
                          'description': '%(issue.data)s',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': 3,
                          'title': 'FilterSkipping'},
    'ForgerySetting': {   'categories': ['security'],
                          'description': '%(issue.data)s',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': 3,
                          'title': 'ForgerySetting'},
    'HeaderDoS': {   'categories': ['security'],
                     'description': '%(issue.data)s',
                     'file': '%(issue.file)s',
                     'line': '%(issue.line)s',
                     'severity': 3,
                     'title': 'HeaderDoS'},
    'I18nXSS': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'I18nXSS'},
    'JRubyXML': {   'categories': ['security'],
                    'description': '%(issue.data)s',
                    'file': '%(issue.file)s',
                    'line': '%(issue.line)s',
                    'severity': 3,
                    'title': 'JRubyXML'},
    'JSONEncoding': {   'categories': ['security'],
                        'description': '%(issue.data)s',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': 3,
                        'title': 'JSONEncoding'},
    'JSONParsing': {   'categories': ['security'],
                       'description': '%(issue.data)s',
                       'file': '%(issue.file)s',
                       'line': '%(issue.line)s',
                       'severity': 3,
                       'title': 'JSONParsing'},
    'LinkTo': {   'categories': ['security'],
                  'description': '%(issue.data)s',
                  'file': '%(issue.file)s',
                  'line': '%(issue.line)s',
                  'severity': 3,
                  'title': 'LinkTo'},
    'LinkToHref': {   'categories': ['security'],
                      'description': '%(issue.data)s',
                      'file': '%(issue.file)s',
                      'line': '%(issue.line)s',
                      'severity': 3,
                      'title': 'LinkToHref'},
    'MailTo': {   'categories': ['security'],
                  'description': '%(issue.data)s',
                  'file': '%(issue.file)s',
                  'line': '%(issue.line)s',
                  'severity': 3,
                  'title': 'MailTo'},
    'MassAssignment': {   'categories': ['security'],
                          'description': '%(issue.data)s',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': 3,
                          'title': 'MassAssignment'},
    'MimeTypeDoS': {   'categories': ['security'],
                       'description': '%(issue.data)s',
                       'file': '%(issue.file)s',
                       'line': '%(issue.line)s',
                       'severity': 3,
                       'title': 'MimeTypeDoS'},
    'ModelAttrAccessible': {   'categories': ['security'],
                               'description': '%(issue.data)s',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': 3,
                               'title': 'ModelAttrAccessible'},
    'ModelAttributes': {   'categories': ['security'],
                           'description': '%(issue.data)s',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': 3,
                           'title': 'ModelAttributes'},
    'ModelSerialize': {   'categories': ['security'],
                          'description': '%(issue.data)s',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': 3,
                          'title': 'ModelSerialize'},
    'NestedAttributes': {   'categories': ['security'],
                            'description': '%(issue.data)s',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': 3,
                            'title': 'NestedAttributes'},
    'NestedAttributesBypass': {   'categories': ['security'],
                                  'description': '%(issue.data)s',
                                  'file': '%(issue.file)s',
                                  'line': '%(issue.line)s',
                                  'severity': 3,
                                  'title': 'NestedAttributesBypass'},
    'NumberToCurrency': {   'categories': ['security'],
                            'description': '%(issue.data)s',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': 3,
                            'title': 'NumberToCurrency'},
    'PermitAttributes': {   'categories': ['security'],
                            'description': '%(issue.data)s',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': 3,
                            'title': 'PermitAttributes'},
    'QuoteTableName': {   'categories': ['security'],
                          'description': '%(issue.data)s',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': 3,
                          'title': 'QuoteTableName'},
    'Redirect': {   'categories': ['security'],
                    'description': '%(issue.data)s',
                    'file': '%(issue.file)s',
                    'line': '%(issue.line)s',
                    'severity': 3,
                    'title': 'Redirect'},
    'RegexDoS': {   'categories': ['security'],
                    'description': '%(issue.data)s',
                    'file': '%(issue.file)s',
                    'line': '%(issue.line)s',
                    'severity': 3,
                    'title': 'RegexDoS'},
    'Render': {   'categories': ['security'],
                  'description': '%(issue.data)s',
                  'file': '%(issue.file)s',
                  'line': '%(issue.line)s',
                  'severity': 3,
                  'title': 'Render'},
    'RenderDoS': {   'categories': ['security'],
                     'description': '%(issue.data)s',
                     'file': '%(issue.file)s',
                     'line': '%(issue.line)s',
                     'severity': 3,
                     'title': 'RenderDoS'},
    'RenderInline': {   'categories': ['security'],
                        'description': '%(issue.data)s',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': 3,
                        'title': 'RenderInline'},
    'ResponseSplitting': {   'categories': ['security'],
                             'description': '%(issue.data)s',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': 3,
                             'title': 'ResponseSplitting'},
    'RouteDoS': {   'categories': ['security'],
                    'description': '%(issue.data)s',
                    'file': '%(issue.file)s',
                    'line': '%(issue.line)s',
                    'severity': 3,
                    'title': 'RouteDoS'},
    'SQL': {   'categories': ['security'],
               'description': '%(issue.data)s',
               'file': '%(issue.file)s',
               'line': '%(issue.line)s',
               'severity': 3,
               'title': 'SQL'},
    'SQLCVEs': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'SQLCVEs'},
    'SSLVerify': {   'categories': ['security'],
                     'description': '%(issue.data)s',
                     'file': '%(issue.file)s',
                     'line': '%(issue.line)s',
                     'severity': 3,
                     'title': 'SSLVerify'},
    'SafeBufferManipulation': {   'categories': ['security'],
                                  'description': '%(issue.data)s',
                                  'file': '%(issue.file)s',
                                  'line': '%(issue.line)s',
                                  'severity': 3,
                                  'title': 'SafeBufferManipulation'},
    'SanitizeMethods': {   'categories': ['security'],
                           'description': '%(issue.data)s',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': 3,
                           'title': 'SanitizeMethods'},
    'SelectTag': {   'categories': ['security'],
                     'description': '%(issue.data)s',
                     'file': '%(issue.file)s',
                     'line': '%(issue.line)s',
                     'severity': 3,
                     'title': 'SelectTag'},
    'SelectVulnerability': {   'categories': ['security'],
                               'description': '%(issue.data)s',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': 3,
                               'title': 'SelectVulnerability'},
    'Send': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': 3,
                'title': 'Send'},
    'SendFile': {   'categories': ['security'],
                    'description': '%(issue.data)s',
                    'file': '%(issue.file)s',
                    'line': '%(issue.line)s',
                    'severity': 3,
                    'title': 'SendFile'},
    'SessionManipulation': {   'categories': ['security'],
                               'description': '%(issue.data)s',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': 3,
                               'title': 'SessionManipulation'},
    'SessionSettings': {   'categories': ['security'],
                           'description': '%(issue.data)s',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': 3,
                           'title': 'SessionSettings'},
    'SimpleFormat': {   'categories': ['security'],
                        'description': '%(issue.data)s',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': 3,
                        'title': 'SimpleFormat'},
    'SingleQuotes': {   'categories': ['security'],
                        'description': '%(issue.data)s',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': 3,
                        'title': 'SingleQuotes'},
    'SkipBeforeFilter': {   'categories': ['security'],
                            'description': '%(issue.data)s',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': 3,
                            'title': 'SkipBeforeFilter'},
    'StripTags': {   'categories': ['security'],
                     'description': '%(issue.data)s',
                     'file': '%(issue.file)s',
                     'line': '%(issue.line)s',
                     'severity': 3,
                     'title': 'StripTags'},
    'SymbolDoSCVE': {   'categories': ['security'],
                        'description': '%(issue.data)s',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': 3,
                        'title': 'SymbolDoSCVE'},
    'TranslateBug': {   'categories': ['security'],
                        'description': '%(issue.data)s',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': 3,
                        'title': 'TranslateBug'},
    'UnsafeReflection': {   'categories': ['security'],
                            'description': '%(issue.data)s',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': 3,
                            'title': 'UnsafeReflection'},
    'ValidationRegex': {   'categories': ['security'],
                           'description': '%(issue.data)s',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': 3,
                           'title': 'ValidationRegex'},
    'WithoutProtection': {   'categories': ['security'],
                             'description': '%(issue.data)s',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': 3,
                             'title': 'WithoutProtection'},
    'XMLDoS': {   'categories': ['security'],
                  'description': '%(issue.data)s',
                  'file': '%(issue.file)s',
                  'line': '%(issue.line)s',
                  'severity': 3,
                  'title': 'XMLDoS'},
    'YAMLParsing': {   'categories': ['security'],
                       'description': '%(issue.data)s',
                       'file': '%(issue.file)s',
                       'line': '%(issue.line)s',
                       'severity': 3,
                       'title': 'YAMLParsing'}}
