issues_data = {   'C0202': {   'categories': ['maintainability', 'readability'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': "class method should have 'cls' as first argument"},
    'C0203': {   'categories': ['maintainability', 'readability'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': "metaclass method should have 'mcs' as first "
                          'argument'},
    'C0321': {   'categories': ['maintainability', 'readability'],
                 'description': '%(issue.data.description)',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'more than one statement per line'},
    'E0100': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': '__init__ is a generator'},
    'E0101': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'explicit return in __init__'},
    'E0104': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'return outside of function'},
    'E0105': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'yield outside of function'},
    'E0106': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'return with argument inside generator'},
    'E0107': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'use of non-existent operator'},
    'E0109': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'duplicate argument name'},
    'E0202': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'hidden attribute'},
    'E0203': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'access before definition'},
    'E0211': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'method without argument'},
    'E0213': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': "method should have 'self' as first argument"},
    'E0235': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': '__exit__ must accept 3 arguments'},
    'E0702': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'illegal value raised'},
    'E0711': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'NotImplemented raised'},
    'E1004': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': "missing arguments to 'super'"},
    'E1111': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': "assigning to function call that doesn't return"},
    'E1121': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'too many arguments'},
    'E1123': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'unexpected keyword argument'},
    'E1124': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'parameter passed as position and keyword argument'},
    'E1200': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'unsupported logging format character'},
    'E1201': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'invalid logging format string'},
    'E1205': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'too many arguments for logging format string'},
    'E1206': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'not enough arguments for logging format string'},
    'E1303': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'expected mapping for format string'},
    'E1305': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'too many arguments for format string'},
    'E1306': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'not enough arguments for format string'},
    'R0201': {   'categories': ['maintainability'],
                 'description': '%(issue.data.description)',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'method could be a function'},
    'W0101': {   'categories': ['maintainability', 'correctness'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'unreachable code'},
    'W0102': {   'categories': ['maintainability', 'correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'dangerous default value as argument'},
    'W0104': {   'categories': ['maintainability', 'correctness'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'statement seems to have no effect'},
    'W0106': {   'categories': ['maintainability', 'correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'expression without assignment'},
    'W0107': {   'categories': ['maintainability', 'correctness'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'unnecessary pass statement'},
    'W0108': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'lambda might not be necessary'},
    'W0109': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'duplicate key in dictionary'},
    'W0110': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'map/filter could be replaced by list comprehension'},
    'W0122': {   'categories': ['correctness', 'security'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'use of exec'},
    'W0150': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': "'finally' may swallow exception"},
    'W0211': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'static method with self/cls as first argument'},
    'W0231': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'init method from base class not called'},
    'W0234': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'iter returns non-iterator'},
    'W0410': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': '__future__ not first in module'},
    'W0603': {   'categories': ['maintainability'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': "use of 'global'"},
    'W0604': {   'categories': ['maintainability'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': "use of 'global' at module level"},
    'W0613': {   'categories': ['readability', 'maintainability'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'unused argument'},
    'W0622': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'redefining builtin'},
    'W0633': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'attempting to unpack non-sequence'},
    'W0701': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'raising a string exception'},
    'W0702': {   'categories': ['maintainability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': "unqualified 'except'"},
    'W0704': {   'categories': ['correctness'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'except without action'},
    'W1111': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'assigning to function call that only returns None'},
    'W1301': {   'categories': ['readability'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'unused key in format string dictionary'},
    'W1501': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'not a valid mode for open'}}
