issues_data = {   'E0101': {   'categories': [   'readability',
                                   'correctness',
                                   'maintainability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'mixed spaces and tabs'},
    'E0111': {   'categories': ['readability', 'maintainability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'indentation not a multiple of four'},
    'E0112': {   'categories': ['readability', 'correctness'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'expected an indented block'},
    'E0113': {   'categories': ['readability', 'correctness'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'unexpected indentation'},
    'E0121': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'continuation line under-indented for hanging '
                          'indent'},
    'E0122': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'continuation line missing indentation or outdented'},
    'E0123': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'closing bracket does not match indentation of '
                          'opening bracket’s line'},
    'E0124': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'closing bracket does not match visual indentation'},
    'E0125': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'continuation line with same indent as next logical '
                          'line'},
    'E0126': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'continuation line over-indented for hanging indent'},
    'E0127': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'continuation line over-indented for visual indent'},
    'E0128': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'continuation line under-indented for visual indent'},
    'E0129': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'visually indented line with same indent as next '
                          'logical line'},
    'E0131': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'continuation line unaligned for hanging indent'},
    'E0133': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'closing bracket is missing indentation'},
    'E0201': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'whitespace after ‘(‘'},
    'E0202': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'whitespace before ‘)’'},
    'E0203': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'whitespace before ‘:’'},
    'E0211': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'whitespace before ‘(‘'},
    'E0221': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'multiple spaces before operator'},
    'E0222': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'multiple spaces after operator'},
    'E0223': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'tab before operator'},
    'E0224': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'tab after operator'},
    'E0225': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'missing whitespace around operator'},
    'E0226': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'missing whitespace around arithmetic operator'},
    'E0227': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'missing whitespace around bitwise or shift '
                          'operator'},
    'E0228': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'missing whitespace around modulo operator'},
    'E0231': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'missing whitespace after ‘,’'},
    'E0241': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'multiple spaces after ‘,’'},
    'E0242': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'tab after ‘,’'},
    'E0251': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'unexpected spaces around keyword / parameter '
                          'equals'},
    'E0261': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'at least two spaces before inline comment'},
    'E0262': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'inline comment should start with ‘# ‘'},
    'E0265': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'block comment should start with ‘# ‘'},
    'E0266': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'too many leading ‘#’ for block comment'},
    'E0271': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'multiple spaces after keyword'},
    'E0272': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'multiple spaces before keyword'},
    'E0273': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'tab after keyword'},
    'E0274': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'tab before keyword'},
    'E0301': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'expected 1 blank line, found 0'},
    'E0302': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'expected 2 blank lines, found 0'},
    'E0303': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'too many blank lines (3)'},
    'E0304': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'blank lines found after function decorator'},
    'E0401': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'multiple imports on one line'},
    'E0501': {   'categories': ['readability'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'line too long'},
    'E0502': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'the backslash is redundant between brackets'},
    'E0701': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'multiple statements on one line (colon)'},
    'E0702': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'multiple statements on one line (semicolon)'},
    'E0703': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'statement ends with a semicolon'},
    'E0704': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'multiple statements on one line'},
    'E0711': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'comparison to None should be ‘if cond is None:’'},
    'E0712': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'comparison to True should be ‘if cond is True:’ or '
                          '‘if cond:’'},
    'E0713': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'test for membership should be ‘not in’'},
    'E0714': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'test for object identity should be ‘is not’'},
    'E0721': {   'categories': ['readability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'do not compare types, use ‘isinstance()’'},
    'E0731': {   'categories': ['readability', 'maintainability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'do not assign a lambda expression, use a def'},
    'E0901': {   'categories': ['correctness'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'syntax / indentation error'},
    'E0902': {   'categories': ['correctness'],
                 'description': '%(issue.data.description)s',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 1,
                 'title': 'IOError'},
    'W0191': {   'categories': ['readability', 'maintainability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 2,
                 'title': 'indentation contains tabs'},
    'W0291': {   'categories': ['readability', 'maintainability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'trailing whitespace'},
    'W0292': {   'categories': ['readability', 'maintainability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'no newline at end of file'},
    'W0293': {   'categories': ['readability', 'maintainability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'blank line contains whitespace'},
    'W0391': {   'categories': ['readability', 'maintainability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 4,
                 'title': 'blank line at end of file'},
    'W0601': {   'categories': ['readability', 'maintainability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': ".has_key() is deprecated, use 'in'"},
    'W0602': {   'categories': ['readability', 'maintainability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'deprecated form of raising an exception'},
    'W0603': {   'categories': ['readability', 'maintainability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': '‘<>’ is deprecated, use ‘!=’'},
    'W0604': {   'categories': ['readability', 'maintainability'],
                 'description': '',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': 3,
                 'title': 'backticks are deprecated, use ‘repr()’'}}
