issues_data = {   'assert code_injection': {   'categories': ['security'],
                                 'description': 'Assert Code Injection '
                                                'detected',
                                 'file': '%(issue.file)s',
                                 'line': '%(issue.line)s',
                                 'severity': '1',
                                 'title': 'Assert Code Injection'},
    'code_injection': {   'categories': ['security'],
                          'description': 'Code Injection detected',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'Code Injection'},
    'command_injection': {   'categories': ['security'],
                             'description': 'Command Injection detected',
                             'file': '%(issue.file)s',
                             'line': '%(issue.line)s',
                             'severity': '1',
                             'title': 'Command Injection'},
    'create_function code_injection': {   'categories': ['security'],
                                          'description': 'Create Function Code '
                                                         'Injection detected',
                                          'file': '%(issue.file)s',
                                          'line': '%(issue.line)s',
                                          'severity': '1',
                                          'title': 'Create Function Code '
                                                   'Injection'},
    'eval code_injection': {   'categories': ['security'],
                               'description': 'Eval Code Injection detected',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': '1',
                               'title': 'Eval Code Injection'},
    'file_disclosure': {   'categories': ['security'],
                           'description': 'File disclosure detected',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': '1',
                           'title': 'File disclosure'},
    'file_inclusion': {   'categories': ['security'],
                          'description': 'File inclusion detected',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '2',
                          'title': 'File Inclusion'},
    'header_injection': {   'categories': ['security'],
                            'description': 'Header Injection detected',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '1',
                            'title': 'Header Injection'},
    'idor': {   'categories': ['security'],
                'description': 'Insecure Direct Object Reference detected',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Insecure Direct Object Reference'},
    'ldap_injection': {   'categories': ['security'],
                          'description': 'LDAP Injection detected',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'LDAP Injection'},
    'mail command_injection': {   'categories': ['security'],
                                  'description': 'Mail Command Injection '
                                                 'detected',
                                  'file': '%(issue.file)s',
                                  'line': '%(issue.line)s',
                                  'severity': '1',
                                  'title': 'Mail Command Injection'},
    'path_traversal': {   'categories': ['security'],
                          'description': 'Path Traversal detected',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': '1',
                          'title': 'Path traversal'},
    'redos': {   'categories': ['security'],
                 'description': 'Redos detected',
                 'file': '%(issue.file)s',
                 'line': '%(issue.line)s',
                 'severity': '1',
                 'title': 'Redos'},
    'session_fixation': {   'categories': ['security'],
                            'description': 'Session fixation detected',
                            'file': '%(issue.file)s',
                            'line': '%(issue.line)s',
                            'severity': '2',
                            'title': 'Session fixation'},
    'sql_injection': {   'categories': ['security'],
                         'description': 'SQL Injection detected',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': '1',
                         'title': 'SQL Injection'},
    'w32api command_injection': {   'categories': ['security'],
                                    'description': 'w32api Command Injection '
                                                   'detected',
                                    'file': '%(issue.file)s',
                                    'line': '%(issue.line)s',
                                    'severity': '1',
                                    'title': 'w32api Command Injection'},
    'xml_injection': {   'categories': ['security'],
                         'description': 'XML Injection detected',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': '1',
                         'title': 'XML Injection'},
    'xss': {   'categories': ['security'],
               'description': 'Cross-Site Scripting detected',
               'file': '%(issue.file)s',
               'line': '%(issue.line)s',
               'severity': '1',
               'title': 'XSS'}}
