issues_data = {   'CWE-200': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-200'},
    'CWE-215': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-215'},
    'CWE-22': {   'categories': ['security'],
                  'description': '%(issue.data)s',
                  'file': '%(issue.file)s',
                  'line': '%(issue.line)s',
                  'severity': 3,
                  'title': 'CWE-22'},
    'CWE-295': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-295'},
    'CWE-311': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-311'},
    'CWE-327': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-327'},
    'CWE-532': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-532'},
    'CWE-539': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-539'},
    'CWE-676': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-676'},
    'CWE-693': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-693'},
    'CWE-695': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-695'},
    'CWE-749': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-749'},
    'CWE-757': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-757'},
    'CWE-789': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-789'},
    'CWE-922': {   'categories': ['security'],
                   'description': '%(issue.data)s',
                   'file': '%(issue.file)s',
                   'line': '%(issue.line)s',
                   'severity': 3,
                   'title': 'CWE-922'},
    'CWE-95': {   'categories': ['security'],
                  'description': '%(issue.data)s',
                  'file': '%(issue.file)s',
                  'line': '%(issue.line)s',
                  'severity': 3,
                  'title': 'CWE-95'}}
