issues_data = {   'G101': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Look for hard coded credentials'},
    'G102': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Bind to all interfaces'},
    'G103': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Audit the use of unsafe block'},
    'G104': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Audit errors not checked'},
    'G106': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Audit the use of ssh.InsecureIgnoreHostKey'},
    'G107': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Url provided to HTTP request as taint input'},
    'G108': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Profiling endpoint automatically exposed on '
                         '/debug/pprof'},
    'G109': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Potential Integer overflow made by strconv.Atoi '
                         'result conversion to int16/3'},
    'G110': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Potential DoS vulnerability via decompression bomb'},
    'G201': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'SQL query construction using format string'},
    'G202': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'SQL query construction using string concatenation'},
    'G203': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Use of unescaped data in HTML templates'},
    'G204': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Audit use of command execution'},
    'G301': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Poor file permissions used when creating a '
                         'directory'},
    'G302': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Poor file permissions used with chmod'},
    'G303': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Creating tempfile using a predictable path'},
    'G304': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'File path provided as taint input'},
    'G305': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'File traversal when extracting zip archive'},
    'G306': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Poor file permissions used when writing to a new '
                         'file'},
    'G307': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Deferring a method which returns an error'},
    'G401': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Detect the usage of DES, RC4, MD5 or SHA1'},
    'G402': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Look for bad TLS connection settings'},
    'G403': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Ensure minimum RSA key length of 2048 bits'},
    'G404': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Insecure random number source (rand)'},
    'G501': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Import blocklist: crypto/md5'},
    'G502': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Import blocklist: crypto/des'},
    'G503': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Import blocklist: crypto/rc4'},
    'G504': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Import blocklist: net/http/cgi'},
    'G505': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Import blocklist: crypto/sha1'},
    'G601': {   'categories': ['security'],
                'description': '%(issue.data)s',
                'file': '%(issue.file)s',
                'line': '%(issue.line)s',
                'severity': '1',
                'title': 'Implicit memory aliasing of items from a range '
                         'statement'}}
