issues_data = {   'DoctestSyntaxError': {   'categories': ['correctness'],
                              'description': '%(issue.data.description)s',
                              'file': '%(issue.file)s',
                              'line': '%(issue.line)s',
                              'severity': 2,
                              'title': 'syntax error in doctest'},
    'ImportShadowedByLoopVar': {   'categories': [   'correctness',
                                                     'maintainability'],
                                   'description': '%(issue.data.description)s',
                                   'file': '%(issue.file)s',
                                   'line': '%(issue.line)s',
                                   'severity': 2,
                                   'title': 'import shadowed by loop variable'},
    'ImportStarUsed': {   'categories': ['readability', 'maintainability'],
                          'description': '%(issue.data.description)s',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': 3,
                          'title': 'wildcard (*) import used'},
    'Redefined': {   'categories': ['maintainability', 'correctness'],
                     'description': '%(issue.data.description)s',
                     'file': '%(issue.file)s',
                     'line': '%(issue.line)s',
                     'severity': 2,
                     'title': 'redefined object'},
    'RedefinedInListComp': {   'categories': ['correctness', 'readability'],
                               'description': '%(issue.data.description)s',
                               'file': '%(issue.file)s',
                               'line': '%(issue.line)s',
                               'severity': 2,
                               'title': 'redefined in list comprehension'},
    'RedefinedWhileUnused': {   'categories': [   'readability',
                                                  'maintainability',
                                                  'correctness',
                                                  'performance'],
                                'description': '%(issue.data.description)s',
                                'file': '%(issue.file)s',
                                'line': '%(issue.line)s',
                                'severity': 2,
                                'title': 'redefined while unused'},
    'UndefinedExport': {   'categories': ['correctness'],
                           'description': '%(issue.data.description)s',
                           'file': '%(issue.file)s',
                           'line': '%(issue.line)s',
                           'severity': 1,
                           'title': 'undefined export'},
    'UndefinedLocal': {   'categories': ['correctness'],
                          'description': '%(issue.data.description)s',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': 1,
                          'title': 'undefined local variable'},
    'UndefinedName': {   'categories': ['correctness'],
                         'description': '%(issue.data.description)s',
                         'file': '%(issue.file)s',
                         'line': '%(issue.line)s',
                         'severity': 1,
                         'title': 'undefined variable'},
    'UnusedImport': {   'categories': [   'readability',
                                          'maintainability',
                                          'performance'],
                        'description': '%(issue.data.description)s',
                        'file': '%(issue.file)s',
                        'line': '%(issue.line)s',
                        'severity': 3,
                        'title': 'unused import'},
    'UnusedVariable': {   'categories': [   'readability',
                                            'maintainability',
                                            'performance'],
                          'description': '%(issue.data.description)s',
                          'file': '%(issue.file)s',
                          'line': '%(issue.line)s',
                          'severity': 3,
                          'title': 'unused variable'}}
